TERMUX_PKG_HOMEPAGE=https://aomedia.org/
TERMUX_PKG_DESCRIPTION="AV1 Video Codec Library"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE, PATENTS"
TERMUX_PKG_MAINTAINER="@atri"
TERMUX_PKG_VERSION=3.4.0
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=file:///home/$USER/neoterm-packages/opensources/aom-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=de30fee63bf5c41d25928153951723211e789762ce451c16d406fbb7ccf101bf
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_INSTALL_LIBDIR=lib
"
